name: MuleSoft CloudHub 2.0 Deployment

on:
  push:
    branches:
      - main

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build Mule App
        run: mvn clean package

      - name: Deploy to CloudHub 2.0
        run: |
          mvn clean deploy -DmuleDeploy \
          -DclientId=${{ secrets.ANYPOINT_CLIENT_ID }} \
          -DclientSecret=${{ secrets.ANYPOINT_CLIENT_SECRET }}
